services:
  selenium-hub:
    image: selenium/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  selenium-node-chrome:
    image: selenium/node-chrome:4.10.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
  anti:
    image: minhvh/anti:latest
    container_name: anti
    platform: linux/amd64
    ports:
      - "8000:80"
      - "5901:5901"
    volumes:
      - .:/app
      - ./entrypoint.sh:/entrypoint.sh
      - ./.docker/app.conf:/etc/nginx/conf.d/app.conf
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - PROFILE_ID=67eeb053a9cb6a7191579b8b
      - TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2VlYWJmOGJkODY2YjdjM2Y2NmIzZjEiLCJ0eXBlIjoiZGV2Iiwiand0aWQiOiI2N2VlYWMyNjcwZTM0MDBhNWY2YjdkZmUifQ.tUvpgtJL0swAUinAx1XIeWt4OQMjBqszIciDPKoE9Nk

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - anti
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYmE2MDA4YWFmN2U2YzQ4MGRjODA1N2QyYTk0ODk3NDUiLCJ0IjoiYjJkMTQwYzctMGNiNy00NjY0LThiNjctMTBmY2JhY2FlYTFlIiwicyI6Ik1qbGxNekV5TXpNdE16Wm1aaTAwTWpjeExXRTNaRGd0TldNMk9XRTNOalEwTmpSaCJ9
    command: tunnel run

