services:
  orbita-app:
    image: minhvh/anti:latest
    container_name: anti
    platform: linux/amd64
    ports:
      - "9000:80"
      - "8000:8000"
      - "5901:5901"
      - "3500:3500"
    volumes:
      - .:/app
      - ./entrypoint.sh:/entrypoint.sh
      - ./.docker/app.conf:/etc/nginx/conf.d/app.conf
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - PROFILE_ID=67eeb053a9cb6a7191579b8b
      - TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2VlYWJmOGJkODY2YjdjM2Y2NmIzZjEiLCJ0eXBlIjoiZGV2Iiwiand0aWQiOiI2N2VlYWMyNjcwZTM0MDBhNWY2YjdkZmUifQ.tUvpgtJL0swAUinAx1XIeWt4OQMjBqszIciDPKoE9Nk
 