name: 'Start server'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Start server by running docker-compose'
      run: docker compose up -d
      shell: bash

    - name: 'Wait for server to be ready'
      run: |
        while ! curl -s http://localhost:9000 > /dev/null; do
          echo "Waiting for server..."
          sleep 5
        done
        resp=$(curl http://localhost:9000/api/ping)
        echo "Response: $resp"
      shell: bash

    - name: 'Print public URL'
      run: |
        sleep 5
        echo  "Public URL: $(curl -s http://localhost:4040/api/tunnels)"
        
        echo "Waiting for ngrok..."
        echo "Public URL: $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
      shell: bash

    - name: 'Keep alive'
      run: sleep 300
      shell: bash