name: 'Start server'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Start server by running docker-compose'
      run: docker compose up -d
      shell: bash

    - name: 'Wait for server to be ready'
      run: docker compose logs -f --tail 0
      shell: bash