name: 'Start server'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Start server by running docker-compose'
      run: docker compose up -d
      shell: bash

    - name: 'Wait for server to be ready'
      run: |
        while ! curl -s http://localhost:9000 > /dev/null; do
          echo "Waiting for server..."
          sleep 1
        done
        resp=$(curl http://localhost:9000/api/ping)
        echo "Response: $resp"
        echo "IP Address: $(curl -s ifconfig.me)"
      shell: bash

    - name: 'Print public URL'
      run: |
        for i in {1..5}; do
          res=$(curl -s http://localhost:4040/api/tunnels)
          https=$(grep -o 'https://[^"]*' <<< "$res" | head -n1)
          tcp=$(grep -o 'tcp://[^"]*' <<< "$res" | head -n1)
          [[ $https || $tcp ]] && break
          sleep 1
        done
        [[ $https || $tcp ]] || { echo "❌ ngrok public_url not found"; exit 1; }
        echo "✅ Public URL: $https"
        echo "✅ TCP URL: $tcp"
      shell: bash

    - name: 'Keep alive'
      run: sleep 300
      shell: bash